import React from 'react';
import { Code2, Package, Play } from 'lucide-react';

export default function ShowcaseCards() {

  const cards = [
    {
      id: 1,
      icon: Code2,
      title: 'Prebuilt UI Components',
      description: 'Use high-quality, pre-designed components ready to drop into your project.',
    },
    {
      id: 2,
      icon: Package,
      title: 'AI Generated Components',
      description: 'Create unique, custom components generated by AI based on your specific needs.',
    },
    {
      id: 3,
      icon: Play,
      title: 'Customizable Props',
      description: 'Easily adjust colors, sizes, and variations to match your design system.',
    },
    {
      id: 4,
      icon: Code2,
      title: 'Clean JSX Code',
      description: 'Copy production-ready JSX directly into your project — zero boilerplate.',
    },
    {
      id: 5,
      icon: Package,
      title: 'NPM Library',
      description: 'Import VirtualUI components with a simple npm install command.',
    },
    {
      id: 6,
      icon: Play,
      title: 'Live Preview',
      description: 'Instantly preview AI-generated components before exporting your code.',
    }
  ];

  return (
    <div className="py-16 bg-slate-950/20 flex flex-col items-center justify-center p-6 w-full relative">
      {/* Background decoration orbs for section depth */}
      <div className="absolute top-1/2 left-0 w-80 h-80 bg-cyan-500/5 rounded-full blur-[100px] -z-10 pointer-events-none"></div>
      <div className="absolute bottom-0 right-0 w-80 h-80 bg-teal-500/5 rounded-full blur-[100px] -z-10 pointer-events-none"></div>

      <div className="text-center mb-10 relative">
        <p className="text-cyan-400 text-xs sm:text-sm font-semibold tracking-widest uppercase mb-2">WHAT'S INSIDE</p>
        <h2 className="text-2xl sm:text-3xl font-semibold tracking-tight text-white">
          Powering Your UI Development
        </h2>
        <p className="text-slate-400 mt-2.5 text-xs sm:text-sm max-w-xl mx-auto">
          Everything you need to create, prototype, and build production-ready user interfaces instantly.
        </p>
      </div>

      <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-6 max-w-6xl w-full">
        {cards.map((card) => {
          const IconComponent = card.icon;
          return (
            <div
              key={card.id}
              className="group relative bg-slate-900/30 border border-slate-800/80 hover:border-cyan-500/30 rounded-2xl p-8 hover:bg-slate-900/50 transition-all duration-300 hover:shadow-[0_8px_30px_rgba(0,0,0,0.3)] hover:-translate-y-1 overflow-hidden"
            >
              {/* Subtle hover gradient backdrop inside card */}
              <div className="absolute inset-0 bg-gradient-to-br from-cyan-500/5 via-transparent to-transparent opacity-0 group-hover:opacity-100 transition-opacity duration-500"></div>

              {/* Icon Container */}
              <div className="mb-6 relative z-10">
                <div className="w-12 h-12 bg-cyan-950/40 border border-cyan-500/10 rounded-xl flex items-center justify-center group-hover:scale-110 group-hover:border-cyan-400/30 group-hover:bg-cyan-500/10 transition-all duration-300 shadow-[0_0_15px_rgba(6,182,212,0.03)] group-hover:shadow-[0_0_20px_rgba(6,182,212,0.15)]">
                  <IconComponent className="w-6 h-6 text-cyan-400 group-hover:text-cyan-300 transition-colors duration-300" strokeWidth={2} />
                </div>
              </div>

              {/* Title */}
              <h3 className="text-white text-base font-semibold mb-2 tracking-tight group-hover:text-cyan-300 transition-colors duration-300 relative z-10">
                {card.title}
              </h3>

              {/* Description */}
              <p className="text-slate-400 text-sm leading-relaxed group-hover:text-slate-300 transition-colors duration-300 relative z-10">
                {card.description}
              </p>
            </div>
          );
        })}
      </div>
    </div>
  );
}